### ISSUE TITLE
Re-labels not visible on “New Entry” pages in Craft 3.4

### ISSUE THREAD

**Issue by rungta** [benjamminf/craft-relabel#47] opened 2020-03-09 15:07 UTC
#### Description

we’re not seeing any field relabels on the _Create a new entry_ pages. Once the entry or draft is saved, the relabaled field titles and instructions kick-in as you would expect. Quite likely related to #42.

#### Steps to reproduce
1. Relabel a field in a section.
2. Create a new entry in that section.

![Screenshot_2020-03-09 Create a new entry (First draft)](https://user-images.githubusercontent.com/663677/76227737-bfe5df00-6245-11ea-8fda-115bc77c2588.png)

![Screenshot_2020-03-09 A should've been relabeled - Craft Plugins Dev](https://user-images.githubusercontent.com/663677/76227726-bc525800-6245-11ea-983b-f3725015161c.png)

#### Other information
- Field Labels version: 1.1.8
- Craft CMS version: 3.4.9
- Browser and version (if the issue affects a specific browser): Firefox 73

**Comment by pvldigital** [comment] 2020-03-10 22:00
Hi @rungta,

It seems like the issue lies with how field labels grabs the context. e.g entry, category, global etc. I have updated the context for new entries, in craft 3.4+, so the labels will correctly be applied. Released in v1.1.9.

**Closed as completed by pvldigital** 2020-03-10 22:00 UTC

**Comment by swey** [comment] 2020-03-23 09:09
@pvldigital I updated to 1.1.19 and I still have that problem

Edit: I figured out that the problem is a localized button label, which you are using to determine the action
